#import "../macros.typ" : *

=== Notational Conventions

These notational conventions are used for presenting syntax:

#let it(x) = text(style: "italic")[#x];

#table(
  columns: 2,
  align: (center,left),
  stroke: none,
  [\[#it("pattern")\]],[optional],
  [{#it("pattern")}],[zero or more repetitions],
  [(#it("pattern"))],[grouping],
  [#it("pat₁") | #it("pat₂")],[choice],
  [$italic("pat")_(chevron.l italic("pat'") chevron.r)$],[difference---elements generated by #it("pat") except those generated by #it("pat'")],
  [#terminal("fibonacci")],[terminal syntax in typewriter font],
)

BNF-like syntax is used throughout, with productions having the form:

#table(
  columns: 3,
  align: (left, center, left),
  stroke: none,
  $italic("nonterm")$, $->$, $italic("alt₁") | italic("alt₂") | dots | italic("altₙ")$
)

In both the lexical and the context-free syntax, there are some
ambiguities that are to be resolved by making grammatical phrases as
long as possible, proceeding from left to right (in shift-reduce
parsing, resolving shift/reduce conflicts by shifting).  In the lexical
syntax, this is the "maximal munch" rule.  In the
context-free syntax, this means that conditionals, let-expressions, and
lambda abstractions extend to the right as far as possible.

=== Lexical Syntax
=== Layout <sec:layout>
=== Literate comments
=== Context-Free Syntax
=== Fixity Resolution <sec:fixity-resolution>