In this chapter, we describe the low-level lexical structure of Haskell.
Most of the details may be skipped in a first reading of the report.

=== Notational Conventions

These notational conventions are used for presenting syntax:

#let it(x) = text(style: "italic")[#x];

#table(
  columns: 2,
  align: (center,left),
  stroke: none,
  [\[#it("pattern")\]],[optional],
  [{#it("pattern")}],[zero or more repetitions],
  [(#it("pattern"))],[grouping],
  [#it("pat₁") | #it("pat₂")],[choice],
  [$italic("pat")_(chevron.l italic("pat'") chevron.r)$],[difference---elements generated by #it("pat") except those generated by #it("pat'")],
  [`fibonacci`],[terminal syntax in typewriter font],
)

Because the syntax in this section describes _lexical_ syntax, all
whitespace is expressed explicitly; there is no
implicit space between juxtaposed symbols.  BNF-like syntax is used
throughout, with productions having the form:

$
  italic("nonterm") -> italic("alt₁") | italic("alt₂") | dots | italic("altₙ")
$


Care must be taken in distinguishing metalogical syntax such as $|$
and $[dots]$ from concrete terminal syntax (given in typewriter font)
such as `|` and `[...]`, although usually the context makes the
distinction clear.

Haskell uses the Unicode @Unicode character set. 
However, source  programs are currently biased toward the ASCII character set used in earlier versions of Haskell.

This syntax depends on properties of the Unicode characters as defined
by the Unicode consortium. 
Haskell compilers are expected to make use of new versions of Unicode as they are made available.

=== Lexical Program Structure

$
  italic("program") &-> { med italic("lexeme") | italic("whitespace") med }\
  italic("lexeme") &-> italic("qvarid") | italic("qconid") | italic("qvarsym") | italic("qconsym") \
  &| italic("literal") | italic("special") | italic("reservedop") | italic("reservedid") \
  italic("literal") &-> italic("integer") | italic("float") | italic("char") | italic("string") \
  italic("special") &-> mono("(") | mono(")") | mono(",") | mono(";") | mono("[") | mono("]") | mono("`") | mono("{") | mono("}") \
  italic("whitespace") &-> italic("whitestuff") { italic("whitestuff") }\
  italic("whitestuff") &-> italic("whitechar") | italic("comment") | italic("ncomment") \
  italic("whitechar") &-> italic("newline") | italic("vertab") | italic("space") | italic("tab") | italic("uniWhite") \
  italic("newline") &-> italic("return") italic("linefeed") | italic("return") | italic("linefeed") | italic("formfeed") \
  italic("return") &-> text("a carriage return")\
  italic("linefeed") &-> text("a line feed")\
  italic("vertab") &-> text("a vertical tab")\
  italic("formfeed") &-> text("a form feed")\
  italic("space") &-> text("a space")\
  italic("tab") &-> text("a horizontal tab")\
  italic("uniWhite") &-> text("any Unicode character defined as whitespace")\
  italic("comment") &-> italic("dashes") [italic("any")_(chevron.l italic("symbol") chevron.r) { italic("any") }] italic("newline") \
  italic("dashes") &-> mono("--") { mono("-") }\
  italic("opencom") &-> mono("{-") \
  italic("closecom") &-> mono("-}")\
  italic("ncomment") &-> italic("opencom") italic("ANYseq") { italic("ncomment") italic("ANYseq") } italic("closecom") \
  italic("ANYseq") &-> { med italic("ANY") med }_(chevron.l { med italic("ANY") med } ( italic("opencom") | italic("closecom") ) { med italic("ANY") med } chevron.r)\
  italic("ANY") &-> italic("graphic") | italic("whitechar") \
  italic("any") &-> italic("graphic") | italic("space") | italic("tab") \
  italic("graphic") &-> italic("small") | italic("large") | italic("symbol") | italic("digit") | italic("special") | mono("\"") | mono("'") \
  italic("small") &-> italic("ascSmall") | italic("uniSmall") | mono("_") \
  italic("ascSmall") &-> mono("a") | mono("b") | dots | mono("z") \
  italic("uniSmall") &-> text("any Unicode lowercase letter")\
  italic("large") &-> italic("ascLarge") | italic("uniLarge") \
  italic("ascLarge") &-> mono("A") | mono("B") | dots | mono("Z")\
  italic("uniLarge") &-> text("any uppercase or titlecase Unicode letter")\
  italic("symbol") &-> italic("ascSymbol") | italic("uniSymbol")_(chevron.l italic("special") | mono("_") | mono("\"") | mono("'") chevron.r)\
  italic("ascSymbol") &-> mono("!") | mono("#") | mono("$") | mono("%") | mono("&") | mono("*") | mono("+") | mono(".")  | mono("/") | mono("<") | mono("=") | mono(">") | mono("?") | mono("@") \
  &| mono("\\") | mono("^") | mono("|") | mono("-") | mono("~") | mono(":") \
  italic("uniSymbol") &-> text("any Unicode symbol or punctuation")\
  italic("digit") &-> italic("ascDigit") | italic("uniDigit") \
  italic("ascDigit") &-> mono("0") | mono("1") | dots | mono("9") \
  italic("uniDigit") &-> text("any Unicode decimal digit")\
  italic("octit") &-> mono("0") | mono("1") | dots | mono("7")\
  italic("hexit") &-> italic("digit") | mono("A") | dots | mono("F") | mono("a") | dots | mono("f")
$

Lexical analysis should use the ``maximal munch'' rule:
at each point, the longest possible lexeme
satisfying the $italic("lexeme")$ production is read.
So, although `case` is a reserved word, `cases` is not.
Similarly, although `=` is reserved, `==` and `~=` are not.  

Any kind of $italic("whitespace")$ is also a proper delimiter for lexemes.

Characters not in the category $italic("ANY")$ are not valid
in Haskell programs and should result in a lexing error.

=== Comments

=== Identifiers and Operators

=== Numeric Literals

$
  italic("decimal")	&-> italic("digit"){italic("digit")} \
  italic("octal")		&-> italic("octit"){italic("octit")} \
  italic("hexadecimal")	&-> italic("hexit"){italic("hexit")} \
  italic("integer")	&-> italic("decimal") \
                &|  mono("0o") italic("octal") | mono("0O") italic("octal") \
                &|  mono("0x") italic("hexadecimal") | mono("0X") italic("hexadecimal") \
  italic("float")	&-> italic("decimal") mono(".") italic("decimal") [ italic("exponent")] \
	        &|  italic("decimal") italic("exponent") \
  italic("exponent")	&-> (mono("e") | mono("E")) [mono("+") | mono("-")] italic("decimal")
$


There are two distinct kinds of numeric literals: integer and
floating.  Integer literals may be given in decimal (the default),
octal (prefixed by `0o` or `0O`) or hexadecimal notation (prefixed by
`0x` or `0X`).
Floating literals are always decimal.
A floating literal must contain digits both before and after the
decimal point; this ensures that a decimal point cannot be mistaken
for another use of the dot character.  Negative numeric literals are
discussed in @sec:operator-applications.  The typing of numeric literals
is discussed in @sec:numeric-literals

=== Character and String Literals

=== Layout

Haskell permits the omission of the braces and semicolons used in several
grammar productions, by
using _layout_ to convey the same information.  This allows both
layout-sensitive and layout-insensitive styles of coding, which
can be freely mixed within one program.  Because layout is
not required, Haskell programs can be straightforwardly
produced by other programs.

The effect of layout on the meaning of a Haskell program
can be completely specified by adding
braces and semicolons in places determined by the layout.  The meaning of
this augmented program is now layout insensitive.

Informally stated, the braces and semicolons are inserted as follows.
The layout (or "off-side") rule takes effect
whenever the open brace is omitted after the keyword `where`, `let`,
`do`, or
`of`.  When this happens, the indentation of the next lexeme (whether
or not on a new line) is remembered and the omitted open brace is
inserted (the whitespace preceding the lexeme may include comments).
For each subsequent line, if it contains only whitespace or is
indented more, then the previous item is continued (nothing is
inserted); if it is indented the same amount, then a new item begins
(a semicolon is inserted); and if it is indented less, then the
layout list ends (a close brace is inserted).  If the indentation of the 
non-brace lexeme immediately following a `where`, `let`, `do` or `of` is less 
than or equal to the current indentation level, then instead of starting 
a layout, an empty list "`{}`" is inserted, and layout processing 
occurs for the current level (i.e. insert a semicolon or close brace). 
A close brace is
also inserted whenever the syntactic category containing the
layout list ends; that is, if an illegal lexeme is encountered at
a point where a close brace would be legal, a close brace is inserted.
The layout rule matches only those open braces that it has
inserted; an explicit open brace must be matched by
an explicit close brace.  Within these explicit open braces,
_no_ layout processing is performed for constructs outside the
braces, even if a line is 
indented to the left of an earlier implicit open brace.

@sec:layout[Section] gives a more precise definition of the layout rules.

Given these rules, a single newline may actually terminate several
layout lists.  Also, these rules permit:
```haskell
f x = let a = 1; b = 2 
          g y = exp2
       in exp1
```
making `a`, `b` and `g` all part of the same layout
list.

As an example, @fig:layout-before shows a (somewhat contrived)
module and @fig:layout-after shows the result of applying the
layout rule to it.  Note in particular: (a)~the line beginning `}};pop`,
where the termination of the previous line invokes three applications
of the layout rule, corresponding to the depth (3) of the nested
`where` clauses, (b)~the close braces in the `where` clause nested
within the tuple and `case` expression, inserted because the end of the
tuple was detected, and (c)~the close brace at the very end, inserted
because of the column 0 indentation of the end-of-file token.

#figure(
  caption: "A sample program",
  supplement: "Figure"
)[
```haskell
module AStack( Stack, push, pop, top, size ) where
data Stack a = Empty 
             | MkStack a (Stack a)

push :: a -> Stack a -> Stack a
push x s = MkStack x s

size :: Stack a -> Int
size s = length (stkToLst s)  where
           stkToLst  Empty         = []
           stkToLst (MkStack x s)  = x:xs where xs = stkToLst s

pop :: Stack a -> (a, Stack a)
pop (MkStack x s)
  = (x, case s of r -> i r where i x = x) -- (pop Empty) is an error

top :: Stack a -> a
top (MkStack x s) = x                     -- (top Empty) is an error
```
]<fig:layout-before>

#figure(
  caption: "Sample program with layout expanded",
  supplement: "Figure"
)[
```haskell
module AStack( Stack, push, pop, top, size ) where
{data Stack a = Empty 
             | MkStack a (Stack a)

;push :: a -> Stack a -> Stack a
;push x s = MkStack x s

;size :: Stack a -> Int
;size s = length (stkToLst s)  where
           {stkToLst  Empty         = []
           ;stkToLst (MkStack x s)  = x:xs where {xs = stkToLst s

}};pop :: Stack a -> (a, Stack a)
;pop (MkStack x s)
  = (x, case s of {r -> i r where {i x = x}}) -- (pop Empty) is an error

;top :: Stack a -> a
;top (MkStack x s) = x                        -- (top Empty) is an error
}
```
]<fig:layout-after>